# 设置端口
server:
  port: 8088

# 设置数据源
spring:
  datasource:
    url: jdbc:mysql://47.111.157.72:3306/runday?characterEncoding=utf-8&Unicode=true
    username: root
    password: root
    # 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置

# 配置mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  # 全局的映射，不用在xml文件写实体类的全路径
  type-aliases-package: com.zhu.pojo
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl